---
- hosts: all
  vars:
    vmdir: /home/fred/vm
    template_disk: rhel72.labs.local-disk1
    vmnet:
      basemac: "52:54"
      gateway: 192.168.122.1
      dns: 192.168.122.1
      netmask: 255.255.255.0
      domain: lab1.local
    qemu:
      machine: pc-i440fx-2.3
      cpu: 2
      mem: 2097152

  tasks:

  - name: Add VM to DNS
    lineinfile: dest=/etc/hosts line='{{ vm_ip_address }} {{ vm_hostname }}' owner=root group=root mode=0644

  - name: Restart DNSmasq
    shell: killall -HUP dnsmasq

  - name: generate MAC address
    shell: openssl rand 4 | xxd -p | sed 's/\(..\)/\1:/g; s/:$//'
    register: macunique

  - name: create VM Disks
    shell: qemu-img create -f qcow2 -b "{{ template_disk }}" "{{ vm_hostname }}"-disk1.qcow2 chdir="{{ vmdir }}"

  - name: inject network-config
    shell: virt-customize -a  "{{ vmdir }}"/"{{ vm_hostname }}"-disk1.qcow2 --run-command 'echo "{{ lookup('template', 'ifconfig.j2') }}" > /etc/sysconfig/network-scripts/ifcfg-eth0'

  - name: hostname
    shell: virt-customize -a  "{{ vmdir }}"/"{{ vm_hostname }}"-disk1.qcow2 --run-command 'echo "{{ vm_hostname }}" > /etc/hostname'

  - name: create Additional Disk
    shell: qemu-img create -f qcow2 "{{ vm_hostname }}"-disk1.qcow2 "{{ disk2 }}"G chdir="{{ vmdir }}"
    when: disk2 is defined

  - name: Create VMs
    virt: name="{{ vm_hostname }}"
          command=define
          xml="{{ lookup('template', 'vm_xml.j2') }}"

  - name: Start VMs
    virt: name="{{ vm_hostname }}"
          state=running
